### ISSUE TITLE
Possibility of OPAM package?

### ISSUE THREAD

**Issue by ix** [nv-vn/TelegraML#1]
Hi, firstly, excellent work! Telegram bots and OCaml, two things I love! Though I haven't tried it yet, given that you use it on an existing bot, it seems fairly complete, if not absolutely so.

I was wondering; Are you planning to add the library to OPAM as a package in the future? It'd make installation a lot more convenient. Keep up the good work!

**Comment by nv-vn** [comment]
There's actually [a PR open for that right now](https://github.com/ocaml/opam-repository/pull/5597) which will hopefully be merged into master in a few hours.
Anyways, glad to see the interest in the project. For the record, it's still missing some of the more obscure features in the API (inline bots, user profile pics, etc.). For now it's fine for developing most basic bots but it's not "'complete."

**Comment by ix** [comment]
Excellent! Thanks for the quick reply. The more obscure features being absent are fine. I have some experience with the API myself and know a few other people who will be interested in this, so it's possible we can contribute them if necessary.
