### ISSUE TITLE
An interface suggestion

### ISSUE THREAD

**Issue by ivg** [nv-vn/TelegraML#10]
[This](https://github.com/nv-vn/TelegraML/blob/master/example/greet.ml#L12) can be rewritten, as:

``` ocaml
    let new_chat_member {Chat.id} {User.first_name} =
      SendMessage (id, "Hello, " ^ first_name, false, None, None)
```

Also, it would be nice to provide functional constructors instead of using explicit constructors. This is a good design choice (as you may later  make them smart) and is more convenient, as it allows to use labeled and optional arguments, with a corresponding `send_message` the example can be rewritten as:

``` ocaml
   let new_chat_member {Chat.id} {User.first_name} = 
      send_message ~id ("Hello, " ^ first_name)
```

Also, it looks like, that since there should be lots of string constructing, it would be nice to make the `send_message` function variadic, i.e., to accept a formatter and arbitrary amount of arguments (this can be implemented using `ksprintf` function from the standard OCaml library). So that finally we can end up with the:

``` ocaml
  let new_chat_member {Chat.id} {User.first_name} = 
    send_message ~id "Hello, %s"  first_name
```

**Comment by nv-vn** [comment]
> This can be rewritten, as:...

Oh nice, didn't realize that works! Thanks for showing me

> Also, it would be nice to provide functional constructors instead of using explicit constructors.

I've had plans to do something kinda like this, but haven't fully decided how to do it. ([Check out this issue](https://github.com/nv-vn/TelegraML/issues/4). The problem that the first comment is talking about is that when you sequence different commands with "callbacks" (i.e. `GetMe of (User.user Result.result -> action`) there needs to be a way of doing that without having to fall back to explicit data constructors. I was considering making an optional argument, like `?and_then:(User.User Result.result -> action)` and then having an operator to make that more concise (which I was going to use `>>=` for). But looking back, it would probably make more sense to define a new operator for that to avoid confusion. Any ideas for this? Also, any thoughts of using a final `()`? I'm not sure how else I could write functions like `get_me` (unless the `~and_then` is required).

> it would be nice to make the send_message function variadic

This actually sounds like a great idea, as long as it doesn't interfere with normal usage/make the function awkward to use I'll go ahead and implement this -- how well do variadic functions play with optional parameters?

Anyways, thanks for the suggestions. I'll try to experiment with the best ways of implementing most of this and see how well I can get it to fit along with the current interface.

**Comment by nv-vn** [comment]
Okay, I've finished most of the work involved in this... I'm still not 100% happy with the code I've written for this issue, but for the most part it seems to work well. I'll close this issue for now but I'm not going to release these changes until I've decided that I'm happy with them.

@ivg Any specific suggestions for how I should make the interface better?

**Comment by ivg** [comment]
Great work!

I've added few comments directly to the commits.

**Comment by ivg** [comment]
> This actually sounds like a great idea, as long as it doesn't interfere with normal usage/make the function awkward to use I'll go ahead and implement this -- how well do variadic functions play with optional parameters?

It should work, but variadic functions will always cost something, as in case of error the compiler messages are sometimes either cryptic, or useless (remember this `unsound type` messages). But, the expressibility is great, so it can be considered a fair price.
